In [1]:
from sklearn.datasets import load_boston

boston = load_boston();

In [9]:
boston_data_X = boston["data"];
boston_target_y = boston["target"]

In [14]:
from sklearn.preprocessing import scale

boston_data_X = scale(boston_data_X)

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle = True, random_state = 42)

In [21]:
import numpy as np
p_array = np.linspace(1, 10, 200)

In [33]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score

scores = []


for p in p_array:
    scores.append(
        cross_val_score(
            estimator=KNeighborsRegressor(
                n_neighbors=5,
                weights='distance',
                metric='minkowski',
                p=p),
            X=boston_data_X,
            y=boston_target_y,
            cv=kf,
            scoring='neg_mean_squared_error'))


In [34]:
scores[:5]

[array([-20.21899107, -12.49567191, -17.22129105, -11.83373336,
        -18.38354627]),
 array([-20.22607648, -12.57429075, -17.43647464, -12.07494178,
        -19.72740989]),
 array([-20.13329413, -12.65479751, -17.68764499, -11.92277511,
        -19.45497299]),
 array([-20.20518452, -12.96135285, -17.65835017, -11.91533174,
        -19.48836227]),
 array([-19.93196196, -12.90136373, -18.02078301, -11.95450061,
        -19.56667956])]

In [38]:
scores_mean = np.mean(scores, axis=1)
scores_mean[:5]

array([-16.03064673, -16.40783871, -16.37069695, -16.44571631,
       -16.47505777])

In [39]:
np.max(scores_mean)
scores_mean[:5]

array([-16.03064673, -16.40783871, -16.37069695, -16.44571631,
       -16.47505777])

In [37]:
p_array[np.argmax(scores_mean)]

1.0